
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/agendaprof_db?useSSL=false&serverTimeZone=UTC
    username: root
    password: senha123

  jpa:
    show-sql: true

    properties:
      hibernate:
        format_sql: true
